[package]
name = "untitled"
version = "0.1.0"
build = "build.rs"
edition = "2021"

[dependencies]
slint = "1.6.0"
gap-buffer = "0.1.0"
regex = "1.10.4"
log = "0.4.21"

[build-dependencies]
slint-build = "1.6.0"