import { Themes } from "styling.slint";

export component BetterButton inherits TouchArea {
    in property<image> img;
    in property<image> hover: img;

    states [
        active when self.has-hover: {
            icon.source: hover;
        }
    ]
    icon := Image {
        colorize: Themes.selected.font-color;
        width: root.width;
        height: root.height;
        source: img;
    }
}